// altmult_complex_18_mrd.v

// Generated using ACDS version 15.1 185

`timescale 1 ps / 1 ps
module altmult_complex_18_mrd (
		input  wire [17:0] dataa_real,  //  complex_input.dataa_real
		input  wire [17:0] dataa_imag,  //               .dataa_imag
		input  wire [15:0] datab_real,  //               .datab_real
		input  wire [15:0] datab_imag,  //               .datab_imag
		input  wire        clock,       //               .clk
		output wire [33:0] result_real, // complex_output.result_real
		output wire [33:0] result_imag  //               .result_imag
	);

	altmult_complex_18_mrd_altmult_complex_151_id3q2ma altmult_complex_0 (
		.dataa_real  (dataa_real),  //  complex_input.dataa_real
		.dataa_imag  (dataa_imag),  //               .dataa_imag
		.datab_real  (datab_real),  //               .datab_real
		.datab_imag  (datab_imag),  //               .datab_imag
		.clock       (clock),       //               .clk
		.result_real (result_real), // complex_output.result_real
		.result_imag (result_imag)  //               .result_imag
	);

endmodule
